{{- range $apps, $app := .Values.environments }} 
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argocd.argoproj.io/instance: applications-dev
  name: {{ $app.name }}
  namespace: default
spec:
  destination:
    namespace: {{ $app.name }}
    server: >-
      https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: {{ $app.name }}
      valueFiles:
        - values.yaml
      version: v3
    path: charts/hello-world
    repoURL: >-
      https://github.com/ojp2/preview-environ.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - Validate=true
      - CreateNamespace=true
{{- end }}
